apiVersion: v2
appVersion: 0.1.0
description: A Helm chart for Kubernetes
name: kelm
type: application
version: 0.1.0

dependencies:
- name: common
  version: 2.x.x
  repository: oci://ghcr.io/riftonix/helm-shared/charts
