image:
  registry: ghcr.io
  repository: riftonix/kelm
  pullPolicy: IfNotPresent
  tag: "0.1.1"

serviceAccount:
  create: true
  annotations: {}
  name: ""

microservice:
  envs:
    IGNORED_NAMESPACES: >
      default,
      kube-system,
      kube-node-lease,
      kube-public,
      cert-manager

resources:
  requests:
    cpu: 200m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 128Mi
